# Generated by Django 4.0.2 on 2022-02-11 11:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Doctor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "consultation_type",
                    models.CharField(
                        choices=[("clinical", "Clinical"), ("online", "Online")],
                        default="online",
                        max_length=50,
                        verbose_name="Consultation Type",
                    ),
                ),
                (
                    "consultation_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Consultation Price",
                    ),
                ),
                (
                    "insurance_company",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Insurance Company",
                    ),
                ),
                (
                    "insurance_number",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Insurance Number",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
