# Generated by Django 4.0.2 on 2022-02-11 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("doctor", "0003_timeslot"),
    ]

    operations = [
        migrations.AlterField(
            model_name="timeslot",
            name="doctor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="doctor.doctor"
            ),
        ),
    ]
